Models/AppDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace MVC_1.Models
{
    public class AppDbContext : DbContext
    {
        public AppDbContext (DbContextOptions<AppDbContext> options) : base(options)
        {

        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }
    }
}

Models/ErrorViewModel.cs
using System;

namespace MVC_1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Areas/Database/Controllers/DbManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_1.Models;

namespace MVC_1.Areas.Database.Controllers
{
    [Area("Database")]
    [Route("/database-manage/[action]")]
    public class DbManageController : Controller
    {
        private readonly AppDbContext _dbcontext;

        public DbManageController (AppDbContext dbContext)
        {
            _dbcontext = dbContext;
        }

        
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult DeleteDb()
        {
            return View();
        }

        [TempData]
        public string StatusMess { get; set;}

        [HttpPost]
        public async Task<IActionResult> DeleteDbAsync()
        {
            var success = await _dbcontext.Database.EnsureDeletedAsync();

            StatusMess = success ? "Xóa thành công" : "Không thể xóa";
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Migrate()
        {
            await _dbcontext.Database.MigrateAsync();

            StatusMess = "Cập nhật Database thành công";
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVC_1.Models;

namespace MVC_1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Areas/Database/Views/DbManage/DeleteDb.cshtml
@{
    ViewData["Title"] = "Xóa database";
}

<p class="alert alert-dange">
    Bạn có chắc chắn xóa?
</p>

<form method="post">
    <button type="submit" class="btn btn-danger">Xóa</button>

    <hr>

    <a asp-action = "Index">Quản lý DB</a>
</form>

Areas/Database/Views/DbManage/Index.cshtml
@using Microsoft.EntityFrameworkCore
@using System.Data

@inject AppDbContext db

@{
    ViewData["Title"] = "Thông tin database";

    var connect = db.Database.GetDbConnection();

    var dbname = connect.Database;
    var can_connect =   db.Database.CanConnect();
}

<partial name = "_AlertMessage"/>

<h1>Thông tin về cơ sở dữ liệu</h1>
<p>- Database: @dbname</p>
<p>- Source: @connect.DataSource</p>
<p>- State: @connect.State</p>

<hr>
<h2>Trạng thái Migration</h2>

@foreach (var item in db.Database.GetAppliedMigrations())
{
    <p>@item</p>
}

@foreach (var item in db.Database.GetPendingMigrations())
{
    <p>@item (pending)</p>
}

@if(!can_connect){
    <p class = "alert alert-danger">Không có khả năng</p>
}

@if(db.Database.GetPendingMigrations().Any())
{
    <form method="post">
        <button class="btn btn-success m-t-2" asp-action = "Migrate">Tạo Database(Cập nhật)</button>
    </form>
    
}



@if(can_connect){
    <h2>Các bảng</h2>

    await db.Database.OpenConnectionAsync();

    var table = db.Database.GetDbConnection().GetSchema("Tables");

    <ul>
        @foreach (System.Data.DataRow item in table.Rows)
        {
            <li>@item["TABLE_NAME"]</li>
        }
    </ul>

    

    <a class="btn btn-danger" asp-action = "DeleteDb">Xóa Database: @dbname</a>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_AlertMessage.cshtml
@{
    var message = TempData["StatusMess"] as string;
}

@if(!string.IsNullOrEmpty(message))
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        @message
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>

                    
                </div>
                <partial name = "_MenuManagePartial"/>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVC_1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_MenuManagePartial.cshtml
<!-- Example single danger button -->
<div class="btn-group">
  <a href="#" class="btn btn-waring dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Manage
  </a>
  <div class="dropdown-menu">
    <a class="dropdown-item" asp-area="Database" asp-controller="DbManage" asp-action="Index">Database</a>
</div>